import type { ToastPosition, ToastType, ToastTheme, TransitionType } from 'robot-toast';

export const ROBOT_OPTIONS: readonly { name: string; value: string; path?: string }[] = [
  { name: 'None (no robot)',  value: 'none' },
  { name: 'Wave',             value: 'wave' },
  { name: 'Base',             value: 'base' },
  { name: 'Base 2',           value: 'base2' },
  { name: 'Success',          value: 'success' },
  { name: 'Error',            value: 'error' },
  { name: 'Angry',            value: 'angry' },
  { name: 'Angry 2',          value: 'angry2' },
  { name: 'Shock',            value: 'shock' },
  { name: 'Think',            value: 'think' },
  { name: 'Search',           value: 'search' },
  { name: 'Loading',          value: 'loading' },
  { name: 'Sleep',            value: 'sleep' },
  { name: 'Head Palm',        value: 'head-palm' },
  { name: 'Type',             value: 'type' },
  { name: 'Validation',       value: 'validation' },
  { name: 'Validation 2',     value: 'validation2' },
  { name: 'Bird (SVG)',       value: 'dxd/bird.svg',      path: 'your-project/public/dxd/bird.svg' },
  { name: 'Billy2',       value: 'dxd/billy2.png',     path: 'your-project/public/dxd/billy2.png' },
  { name: 'Jinwoo',       value: 'dxd/jinwoo.png',     path: 'your-project/public/dxd/jinwoo.png' },
  { name: 'Pickachu',       value: 'dxd/pickachu.svg',     path: 'your-project/public/dxd/pickachu.svg' },
  { name: 'Sharingan',       value: 'dxd/sharingan.png',      path: 'your-project/public/dxd/sharingan.png' },
  { name: 'Deadpool',       value: 'dxd/deadpool.gif',      path: 'your-project/public/dxd/deadpool.gif' },
];

export const ROBOTS = ROBOT_OPTIONS.map(o => o.value);

// Export client-side position/type/theme/transition options
export const POSITIONS: readonly ToastPosition[] = [
  'top-right', 'top-left', 'top-center',
  'bottom-right', 'bottom-left', 'bottom-center',
];

export const TYPES: readonly ToastType[] = [
  'default', 'info', 'success', 'warning', 'error',
];

export const THEMES: readonly ToastTheme[] = [
  'light', 'dark', 'colored',
];

export const TRANSITIONS: readonly TransitionType[] = [
  'bounce', 'slide', 'zoom', 'flip',
];

// Shared category palette — consumed by Sidebar, Features page, and per-feature toast styles
export const CATEGORY_THEME: Record<string, { label: string; accent: string; bg: string; text: string }> = {
  robot:       { label: '🤖 Robots',       accent: '#8b5cf6', bg: 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)', text: '#fff' },
  position:    { label: '📍 Positions',    accent: '#06b6d4', bg: 'linear-gradient(135deg, #22d3ee 0%, #0891b2 100%)', text: '#fff' },
  theme:       { label: '🎨 Themes',       accent: '#ec4899', bg: 'linear-gradient(135deg, #f472b6 0%, #db2777 100%)', text: '#fff' },
  type:        { label: '🏷️ Types',        accent: '#10b981', bg: 'linear-gradient(135deg, #34d399 0%, #059669 100%)', text: '#fff' },
  animation:   { label: '✨ Animations',   accent: '#f59e0b', bg: 'linear-gradient(135deg, #fbbf24 0%, #d97706 100%)', text: '#fff' },
  behavior:    { label: '⚙️ Behavior',     accent: '#3b82f6', bg: 'linear-gradient(135deg, #60a5fa 0%, #2563eb 100%)', text: '#fff' },
  interaction: { label: '👆 Interactions', accent: '#ef4444', bg: 'linear-gradient(135deg, #f87171 0%, #dc2626 100%)', text: '#fff' },
  async:       { label: '⏳ Async',        accent: '#6366f1', bg: 'linear-gradient(135deg, #818cf8 0%, #4f46e5 100%)', text: '#fff' },
  styling:     { label: '🎭 Styling',      accent: '#14b8a6', bg: 'linear-gradient(135deg, #2dd4bf 0%, #0d9488 100%)', text: '#fff' },
  other:      { label: '🍞 other-style',  accent: '#0a0a0a', bg: 'linear-gradient(135deg, #27272a 0%, #0a0a0a 100%)', text: '#fff' },
};

// Shared toast style fragments used across FEATURES
const robotStyle = (accent: string) => ({
  background: 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)',
  color: '#fff',
  borderLeft: `4px solid ${accent}`,
  borderRadius: '14px',
  boxShadow: '0 10px 30px -10px rgba(139,92,246,0.5)',
});

const positionStyle = (shadow: string) => ({
  background: 'linear-gradient(135deg, #22d3ee 0%, #0891b2 100%)',
  color: '#fff',
  borderRadius: '14px',
  boxShadow: shadow,
});

const typeStyle = (gradient: string, edge: string) => ({
  background: gradient,
  color: '#fff',
  borderLeft: `4px solid ${edge}`,
  borderRadius: '14px',
  boxShadow: '0 10px 30px -10px rgba(0,0,0,0.25)',
});

// Features data for the Features page
export const FEATURES = [
  // 16 Robot Variants
  {
    id: 'robot-wave',
    name: 'Wave Robot',
    category: 'robot',
    description: 'Friendly waving robot companion',
    codeExample: `import { toast } from 'robot-toast';\nimport { wave } from 'robot-toast/robots';\n\ntoast({\n  message: 'Hello there! 👋',\n  robotVariant: wave,\n  style: {\n    background: 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #60a5fa',\n    borderRadius: '14px',\n  },\n});`,
    properties: { robotVariant: 'wave', message: 'Hello there! 👋', style: robotStyle('#60a5fa') },
  },
  {
    id: 'robot-base',
    name: 'Base Robot',
    category: 'robot',
    description: 'Standard robot variant',
    codeExample: `import { toast } from 'robot-toast';\nimport { base } from 'robot-toast/robots';\n\ntoast({\n  message: 'Base robot loaded',\n  robotVariant: base,\n  style: {\n    background: 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #64748b',\n    borderRadius: '14px',\n  },\n});`,
    properties: { robotVariant: 'base', message: 'Base robot loaded', style: robotStyle('#64748b') },
  },
  {
    id: 'robot-base2',
    name: 'Base 2 Robot',
    category: 'robot',
    description: 'Alternative base variant',
    codeExample: `import { toast } from 'robot-toast';\nimport { base2 } from 'robot-toast/robots';\n\ntoast({\n  message: 'Base 2 activated',\n  robotVariant: base2,\n  style: {\n    background: 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #475569',\n    borderRadius: '14px',\n  },\n});`,
    properties: { robotVariant: 'base2', message: 'Base 2 activated', style: robotStyle('#475569') },
  },
  {
    id: 'robot-success',
    name: 'Success Robot',
    category: 'robot',
    description: 'Happy robot for success messages',
    codeExample: `import { toast } from 'robot-toast';\nimport { success } from 'robot-toast/robots';\n\ntoast.success({\n  message: 'Operation successful!',\n  robotVariant: success,\n  style: {\n    background: 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #10b981',\n    borderRadius: '14px',\n  },\n});`,
    properties: { robotVariant: 'success', message: 'Operation successful!', type: 'success', style: robotStyle('#10b981') },
  },
  {
    id: 'robot-error',
    name: 'Error Robot',
    category: 'robot',
    description: 'Worried robot for error messages',
    codeExample: `import { toast } from 'robot-toast';\nimport { error } from 'robot-toast/robots';\n\ntoast.error({\n  message: 'Something went wrong',\n  robotVariant: error,\n  style: {\n    background: 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #ef4444',\n    borderRadius: '14px',\n  },\n});`,
    properties: { robotVariant: 'error', message: 'Something went wrong', type: 'error', style: robotStyle('#ef4444') },
  },
  {
    id: 'robot-angry',
    name: 'Angry Robot',
    category: 'robot',
    description: 'Angry expression robot',
    codeExample: `import { toast } from 'robot-toast';\nimport { angry } from 'robot-toast/robots';\n\ntoast({\n  message: 'Warning: angry mode',\n  robotVariant: angry,\n  type: 'warning',\n  style: {\n    background: 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #f97316',\n    borderRadius: '14px',\n  },\n});`,
    properties: { robotVariant: 'angry', message: 'Warning: angry mode', type: 'warning', style: robotStyle('#f97316') },
  },
  {
    id: 'robot-angry2',
    name: 'Angry 2 Robot',
    category: 'robot',
    description: 'Alternative angry variant',
    codeExample: `import { toast } from 'robot-toast';\nimport { angry2 } from 'robot-toast/robots';\n\ntoast({\n  message: 'Extra angry!',\n  robotVariant: angry2,\n  style: {\n    background: 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #dc2626',\n    borderRadius: '14px',\n  },\n});`,
    properties: { robotVariant: 'angry2', message: 'Extra angry!', style: robotStyle('#dc2626') },
  },
  {
    id: 'robot-shock',
    name: 'Shock Robot',
    category: 'robot',
    description: 'Surprised robot',
    codeExample: `import { toast } from 'robot-toast';\nimport { shock } from 'robot-toast/robots';\n\ntoast({\n  message: 'Unexpected event!',\n  robotVariant: shock,\n  style: {\n    background: 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #f59e0b',\n    borderRadius: '14px',\n  },\n});`,
    properties: { robotVariant: 'shock', message: 'Unexpected event!', style: robotStyle('#f59e0b') },
  },
  {
    id: 'robot-think',
    name: 'Think Robot',
    category: 'robot',
    description: 'Thoughtful robot',
    codeExample: `import { toast } from 'robot-toast';\nimport { think } from 'robot-toast/robots';\n\ntoast({\n  message: 'Let me think...',\n  robotVariant: think,\n  style: {\n    background: 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #8b5cf6',\n    borderRadius: '14px',\n  },\n});`,
    properties: { robotVariant: 'think', message: 'Let me think...', style: robotStyle('#8b5cf6') },
  },
  {
    id: 'robot-search',
    name: 'Search Robot',
    category: 'robot',
    description: 'Searching robot with magnifying glass',
    codeExample: `import { toast } from 'robot-toast';\nimport { search } from 'robot-toast/robots';\n\ntoast({\n  message: 'Searching...',\n  robotVariant: search,\n  style: {\n    background: 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #06b6d4',\n    borderRadius: '14px',\n  },\n});`,
    properties: { robotVariant: 'search', message: 'Searching...', style: robotStyle('#06b6d4') },
  },
  {
    id: 'robot-loading',
    name: 'Loading Robot',
    category: 'robot',
    description: 'Loading spinner robot',
    codeExample: `import { toast } from 'robot-toast';\nimport { loading } from 'robot-toast/robots';\n\ntoast({\n  message: 'Loading...',\n  robotVariant: loading,\n  autoClose: false,\n  style: {\n    background: 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #6366f1',\n    borderRadius: '14px',\n  },\n});`,
    properties: { robotVariant: 'loading', message: 'Loading...', autoClose: false, style: robotStyle('#6366f1') },
  },
  {
    id: 'robot-sleep',
    name: 'Sleep Robot',
    category: 'robot',
    description: 'Sleeping robot',
    codeExample: `import { toast } from 'robot-toast';\nimport { sleep } from 'robot-toast/robots';\n\ntoast({\n  message: 'Time to sleep',\n  robotVariant: sleep,\n  style: {\n    background: 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #94a3b8',\n    borderRadius: '14px',\n  },\n});`,
    properties: { robotVariant: 'sleep', message: 'Time to sleep', style: robotStyle('#94a3b8') },
  },
  {
    id: 'robot-headpalm',
    name: 'Head Palm Robot',
    category: 'robot',
    description: 'Embarrassed head-palm gesture',
    codeExample: `import { toast } from 'robot-toast';\nimport { headPalm } from 'robot-toast/robots';\n\ntoast({\n  message: 'Oops!',\n  robotVariant: headPalm,\n  style: {\n    background: 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #ec4899',\n    borderRadius: '14px',\n  },\n});`,
    properties: { robotVariant: 'headPalm', message: 'Oops!', style: robotStyle('#ec4899') },
  },
  {
    id: 'robot-typing',
    name: 'Typing Robot',
    category: 'robot',
    description: 'Robot with typing gesture',
    codeExample: `import { toast } from 'robot-toast';\nimport { typing } from 'robot-toast/robots';\n\ntoast({\n  message: 'Typing...',\n  robotVariant: typing,\n  style: {\n    background: 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #14b8a6',\n    borderRadius: '14px',\n  },\n});`,
    properties: { robotVariant: 'typing', message: 'Typing...', style: robotStyle('#14b8a6') },
  },
  {
    id: 'robot-validation',
    name: 'Validation Robot',
    category: 'robot',
    description: 'Validation check robot',
    codeExample: `import { toast } from 'robot-toast';\nimport { validation } from 'robot-toast/robots';\n\ntoast({\n  message: 'Validation passed!',\n  robotVariant: validation,\n  style: {\n    background: 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #22c55e',\n    borderRadius: '14px',\n  },\n});`,
    properties: { robotVariant: 'validation', message: 'Validation passed!', style: robotStyle('#22c55e') },
  },
  {
    id: 'robot-validation2',
    name: 'Validation 2 Robot',
    category: 'robot',
    description: 'Alternative validation variant',
    codeExample: `import { toast } from 'robot-toast';\nimport { validation2 } from 'robot-toast/robots';\n\ntoast({\n  message: 'All checks passed',\n  robotVariant: validation2,\n  style: {\n    background: 'linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #16a34a',\n    borderRadius: '14px',\n  },\n});`,
    properties: { robotVariant: 'validation2', message: 'All checks passed', style: robotStyle('#16a34a') },
  },

  // Position Options
  {
    id: 'position-topright',
    name: 'Top Right Position',
    category: 'position',
    description: 'Display toast in the top-right corner',
    codeExample: `toast({\n  message: 'Top right position',\n  position: 'top-right',\n  style: {\n    background: 'linear-gradient(135deg, #22d3ee 0%, #0891b2 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '8px -8px 24px rgba(6,182,212,0.35)',\n  },\n});`,
    properties: { message: 'Top right position', position: 'top-right', style: positionStyle('8px -8px 24px rgba(6,182,212,0.35)') },
  },
  {
    id: 'position-topleft',
    name: 'Top Left Position',
    category: 'position',
    description: 'Display toast in the top-left corner',
    codeExample: `toast({\n  message: 'Top left position',\n  position: 'top-left',\n  style: {\n    background: 'linear-gradient(135deg, #22d3ee 0%, #0891b2 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '-8px -8px 24px rgba(6,182,212,0.35)',\n  },\n});`,
    properties: { message: 'Top left position', position: 'top-left', style: positionStyle('-8px -8px 24px rgba(6,182,212,0.35)') },
  },
  {
    id: 'position-topcenter',
    name: 'Top Center Position',
    category: 'position',
    description: 'Display toast at the top center',
    codeExample: `toast({\n  message: 'Top center position',\n  position: 'top-center',\n  style: {\n    background: 'linear-gradient(135deg, #22d3ee 0%, #0891b2 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 -8px 24px rgba(6,182,212,0.35)',\n  },\n});`,
    properties: { message: 'Top center position', position: 'top-center', style: positionStyle('0 -8px 24px rgba(6,182,212,0.35)') },
  },
  {
    id: 'position-bottomright',
    name: 'Bottom Right Position',
    category: 'position',
    description: 'Display toast in the bottom-right corner',
    codeExample: `toast({\n  message: 'Bottom right position',\n  position: 'bottom-right',\n  style: {\n    background: 'linear-gradient(135deg, #22d3ee 0%, #0891b2 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '8px 8px 24px rgba(6,182,212,0.35)',\n  },\n});`,
    properties: { message: 'Bottom right position', position: 'bottom-right', style: positionStyle('8px 8px 24px rgba(6,182,212,0.35)') },
  },
  {
    id: 'position-bottomleft',
    name: 'Bottom Left Position',
    category: 'position',
    description: 'Display toast in the bottom-left corner',
    codeExample: `toast({\n  message: 'Bottom left position',\n  position: 'bottom-left',\n  style: {\n    background: 'linear-gradient(135deg, #22d3ee 0%, #0891b2 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '-8px 8px 24px rgba(6,182,212,0.35)',\n  },\n});`,
    properties: { message: 'Bottom left position', position: 'bottom-left', style: positionStyle('-8px 8px 24px rgba(6,182,212,0.35)') },
  },
  {
    id: 'position-bottomcenter',
    name: 'Bottom Center Position',
    category: 'position',
    description: 'Display toast at the bottom center',
    codeExample: `toast({\n  message: 'Bottom center position',\n  position: 'bottom-center',\n  style: {\n    background: 'linear-gradient(135deg, #22d3ee 0%, #0891b2 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 8px 24px rgba(6,182,212,0.35)',\n  },\n});`,
    properties: { message: 'Bottom center position', position: 'bottom-center', style: positionStyle('0 8px 24px rgba(6,182,212,0.35)') },
  },

  // Theme Options
  {
    id: 'theme-light',
    name: 'Light Theme',
    category: 'theme',
    description: 'Light color scheme',
    codeExample: `toast({\n  message: 'Light theme',\n  theme: 'light',\n  style: {\n    background: '#ffffff',\n    color: '#111827',\n    border: '1px solid #e5e7eb',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(0,0,0,0.2)',\n  },\n});`,
    properties: {
      message: 'Light theme',
      theme: 'light',
      style: {
        background: '#ffffff',
        color: '#111827',
        border: '1px solid #e5e7eb',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(0,0,0,0.2)',
      },
    },
  },
  {
    id: 'theme-dark',
    name: 'Dark Theme',
    category: 'theme',
    description: 'Dark color scheme',
    codeExample: `toast({\n  message: 'Dark theme',\n  theme: 'dark',\n  style: {\n    background: '#0f172a',\n    color: '#f1f5f9',\n    border: '1px solid #334155',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(0,0,0,0.5)',\n  },\n});`,
    properties: {
      message: 'Dark theme',
      theme: 'dark',
      style: {
        background: '#0f172a',
        color: '#f1f5f9',
        border: '1px solid #334155',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(0,0,0,0.5)',
      },
    },
  },
  {
    id: 'theme-colored',
    name: 'Colored Theme',
    category: 'theme',
    description: 'Colorful theme based on type',
    codeExample: `toast({\n  message: 'Colored theme',\n  theme: 'colored',\n  type: 'success',\n  style: {\n    background: 'linear-gradient(135deg, #f472b6 0%, #db2777 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(219,39,119,0.4)',\n  },\n});`,
    properties: {
      message: 'Colored theme',
      theme: 'colored',
      type: 'success',
      style: {
        background: 'linear-gradient(135deg, #f472b6 0%, #db2777 100%)',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(219,39,119,0.4)',
      },
    },
  },

  // Toast Type Options
  {
    id: 'type-default',
    name: 'Default Type',
    category: 'type',
    description: 'Default notification type',
    codeExample: `toast({\n  message: 'Default type',\n  type: 'default',\n  style: {\n    background: 'linear-gradient(135deg, #94a3b8 0%, #475569 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #334155',\n    borderRadius: '14px',\n  },\n});`,
    properties: { message: 'Default type', type: 'default', style: typeStyle('linear-gradient(135deg, #94a3b8 0%, #475569 100%)', '#334155') },
  },
  {
    id: 'type-info',
    name: 'Info Type',
    category: 'type',
    description: 'Informational notification',
    codeExample: `toast.info({\n  message: 'Info type notification',\n  style: {\n    background: 'linear-gradient(135deg, #60a5fa 0%, #2563eb 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #1e40af',\n    borderRadius: '14px',\n  },\n});`,
    properties: { message: 'Info type notification', type: 'info', style: typeStyle('linear-gradient(135deg, #60a5fa 0%, #2563eb 100%)', '#1e40af') },
  },
  {
    id: 'type-success',
    name: 'Success Type',
    category: 'type',
    description: 'Success notification',
    codeExample: `toast.success({\n  message: 'Operation successful!',\n  style: {\n    background: 'linear-gradient(135deg, #34d399 0%, #059669 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #047857',\n    borderRadius: '14px',\n  },\n});`,
    properties: { message: 'Operation successful!', type: 'success', style: typeStyle('linear-gradient(135deg, #34d399 0%, #059669 100%)', '#047857') },
  },
  {
    id: 'type-warning',
    name: 'Warning Type',
    category: 'type',
    description: 'Warning notification',
    codeExample: `toast.warning({\n  message: 'Check your input',\n  style: {\n    background: 'linear-gradient(135deg, #fbbf24 0%, #d97706 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #b45309',\n    borderRadius: '14px',\n  },\n});`,
    properties: { message: 'Check your input', type: 'warning', style: typeStyle('linear-gradient(135deg, #fbbf24 0%, #d97706 100%)', '#b45309') },
  },
  {
    id: 'type-error',
    name: 'Error Type',
    category: 'type',
    description: 'Error notification',
    codeExample: `toast.error({\n  message: 'Something went wrong',\n  style: {\n    background: 'linear-gradient(135deg, #f87171 0%, #dc2626 100%)',\n    color: '#fff',\n    borderLeft: '4px solid #991b1b',\n    borderRadius: '14px',\n  },\n});`,
    properties: { message: 'Something went wrong', type: 'error', style: typeStyle('linear-gradient(135deg, #f87171 0%, #dc2626 100%)', '#991b1b') },
  },

  // Feature Demonstrations
  {
    id: 'feature-typing',
    name: 'Typewriter Effect',
    category: 'animation',
    description: 'Characters appear one by one',
    codeExample: `toast({\n  message: 'This appears letter by letter',\n  typeSpeed: 30,\n  style: {\n    background: 'linear-gradient(135deg, #fbbf24 0%, #d97706 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    letterSpacing: '0.02em',\n    boxShadow: '0 10px 30px -10px rgba(217,119,6,0.4)',\n  },\n});`,
    properties: {
      message: 'This appears letter by letter',
      typeSpeed: 30,
      style: {
        background: 'linear-gradient(135deg, #fbbf24 0%, #d97706 100%)',
        color: '#fff',
        borderRadius: '14px',
        letterSpacing: '0.02em',
        boxShadow: '0 10px 30px -10px rgba(217,119,6,0.4)',
      },
    },
  },
  {
    id: 'transition-bounce',
    name: 'Bounce Transition',
    category: 'animation',
    description: 'Springy bounce entry and exit',
    codeExample: `toast({\n  message: 'Boing! Bounce transition',\n  transition: 'bounce',\n  style: {\n    background: 'linear-gradient(135deg, #fbbf24 0%, #d97706 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(217,119,6,0.4)',\n  },\n});`,
    properties: {
      message: 'Boing! Bounce transition',
      transition: 'bounce',
      style: {
        background: 'linear-gradient(135deg, #fbbf24 0%, #d97706 100%)',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(217,119,6,0.4)',
      },
    },
  },
  {
    id: 'transition-slide',
    name: 'Slide Transition',
    category: 'animation',
    description: 'Smooth horizontal slide in and out',
    codeExample: `toast({\n  message: 'Sliding into view',\n  transition: 'slide',\n  style: {\n    background: 'linear-gradient(135deg, #fbbf24 0%, #d97706 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(217,119,6,0.4)',\n  },\n});`,
    properties: {
      message: 'Sliding into view',
      transition: 'slide',
      style: {
        background: 'linear-gradient(135deg, #fbbf24 0%, #d97706 100%)',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(217,119,6,0.4)',
      },
    },
  },
  {
    id: 'transition-zoom',
    name: 'Zoom Transition',
    category: 'animation',
    description: 'Scales up from the center',
    codeExample: `toast({\n  message: 'Zooming in!',\n  transition: 'zoom',\n  style: {\n    background: 'linear-gradient(135deg, #fbbf24 0%, #d97706 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(217,119,6,0.4)',\n  },\n});`,
    properties: {
      message: 'Zooming in!',
      transition: 'zoom',
      style: {
        background: 'linear-gradient(135deg, #fbbf24 0%, #d97706 100%)',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(217,119,6,0.4)',
      },
    },
  },
  {
    id: 'transition-flip',
    name: 'Flip Transition',
    category: 'animation',
    description: '3D flip entry',
    codeExample: `toast({\n  message: 'Flipping in 3D',\n  transition: 'flip',\n  style: {\n    background: 'linear-gradient(135deg, #fbbf24 0%, #d97706 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(217,119,6,0.4)',\n  },\n});`,
    properties: {
      message: 'Flipping in 3D',
      transition: 'flip',
      style: {
        background: 'linear-gradient(135deg, #fbbf24 0%, #d97706 100%)',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(217,119,6,0.4)',
      },
    },
  },
  {
    id: 'feature-progress',
    name: 'Progress Bar',
    category: 'behavior',
    description: 'Countdown progress bar animation',
    codeExample: `toast({\n  message: 'Auto-closes in 5 seconds',\n  hideProgressBar: false,\n  autoClose: 5000,\n  style: {\n    background: 'linear-gradient(135deg, #60a5fa 0%, #2563eb 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(37,99,235,0.4)',\n  },\n});`,
    properties: {
      message: 'Auto-closes in 5 seconds',
      hideProgressBar: false,
      autoClose: 5000,
      style: {
        background: 'linear-gradient(135deg, #60a5fa 0%, #2563eb 100%)',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(37,99,235,0.4)',
      },
    },
  },
  {
    id: 'feature-persistent',
    name: 'Persistent Toast',
    category: 'behavior',
    description: 'Disable auto-close — toast stays until manually dismissed',
    codeExample: `toast({\n  message: 'I will stay until you close me',\n  autoClose: 0,\n  hideProgressBar: true,\n  style: {\n    background: 'linear-gradient(135deg, #1e3a8a 0%, #2563eb 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    borderLeft: '4px solid #fbbf24',\n    boxShadow: '0 10px 30px -10px rgba(30,58,138,0.5)',\n  },\n});`,
    properties: {
      message: 'I will stay until you close me',
      autoClose: 0,
      hideProgressBar: true,
      style: {
        background: 'linear-gradient(135deg, #1e3a8a 0%, #2563eb 100%)',
        color: '#fff',
        borderRadius: '14px',
        borderLeft: '4px solid #fbbf24',
        boxShadow: '0 10px 30px -10px rgba(30,58,138,0.5)',
      },
    },
  },
  {
    id: 'feature-autoclose-short',
    name: 'Quick Close (1.5s)',
    category: 'behavior',
    description: 'Short-lived toast that auto-closes in 1.5 seconds',
    codeExample: `toast({\n  message: 'Gone in a flash',\n  autoClose: 1500,\n  style: {\n    background: 'linear-gradient(135deg, #60a5fa 0%, #2563eb 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(37,99,235,0.4)',\n  },\n});`,
    properties: {
      message: 'Gone in a flash',
      autoClose: 1500,
      style: {
        background: 'linear-gradient(135deg, #60a5fa 0%, #2563eb 100%)',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(37,99,235,0.4)',
      },
    },
  },
  {
    id: 'feature-autoclose-long',
    name: 'Long Display (10s)',
    category: 'behavior',
    description: 'Lingering toast with a 10-second countdown',
    codeExample: `toast({\n  message: 'Take your time reading this',\n  autoClose: 10000,\n  style: {\n    background: 'linear-gradient(135deg, #60a5fa 0%, #2563eb 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(37,99,235,0.4)',\n  },\n});`,
    properties: {
      message: 'Take your time reading this',
      autoClose: 10000,
      style: {
        background: 'linear-gradient(135deg, #60a5fa 0%, #2563eb 100%)',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(37,99,235,0.4)',
      },
    },
  },
  {
    id: 'feature-hide-progress',
    name: 'Hidden Progress Bar',
    category: 'behavior',
    description: 'Auto-closes without showing the countdown bar',
    codeExample: `toast({\n  message: 'No progress bar, just a clean close',\n  hideProgressBar: true,\n  autoClose: 4000,\n  style: {\n    background: 'linear-gradient(135deg, #60a5fa 0%, #2563eb 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(37,99,235,0.4)',\n  },\n});`,
    properties: {
      message: 'No progress bar, just a clean close',
      hideProgressBar: true,
      autoClose: 4000,
      style: {
        background: 'linear-gradient(135deg, #60a5fa 0%, #2563eb 100%)',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(37,99,235,0.4)',
      },
    },
  },
  {
    id: 'feature-pause-hover',
    name: 'Pause on Hover',
    category: 'behavior',
    description: 'Countdown pauses while the cursor is over the toast',
    codeExample: `toast({\n  message: 'Hover over me to pause',\n  pauseOnHover: true,\n  autoClose: 6000,\n  style: {\n    background: 'linear-gradient(135deg, #60a5fa 0%, #2563eb 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(37,99,235,0.4)',\n  },\n});`,
    properties: {
      message: 'Hover over me to pause',
      pauseOnHover: true,
      autoClose: 6000,
      style: {
        background: 'linear-gradient(135deg, #60a5fa 0%, #2563eb 100%)',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(37,99,235,0.4)',
      },
    },
  },
  {
    id: 'feature-pause-focus',
    name: 'Pause on Focus Loss',
    category: 'behavior',
    description: 'Countdown pauses when the window loses focus (try switching tabs)',
    codeExample: `toast({\n  message: 'Switch tabs — my timer pauses',\n  pauseOnFocusLoss: true,\n  autoClose: 8000,\n  style: {\n    background: 'linear-gradient(135deg, #60a5fa 0%, #2563eb 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(37,99,235,0.4)',\n  },\n});`,
    properties: {
      message: 'Switch tabs — my timer pauses',
      pauseOnFocusLoss: true,
      autoClose: 8000,
      style: {
        background: 'linear-gradient(135deg, #60a5fa 0%, #2563eb 100%)',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(37,99,235,0.4)',
      },
    },
  },
  {
    id: 'feature-draggable',
    name: 'Drag & Drop',
    category: 'interaction',
    description: 'Click and drag the toast anywhere',
    codeExample: `toast({\n  message: 'Try dragging me around!',\n  draggable: true,\n  style: {\n    background: 'linear-gradient(135deg, #f87171 0%, #dc2626 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    fontWeight: '600',\n    boxShadow: '0 12px 28px -10px rgba(220,38,38,0.45)',\n  },\n});`,
    properties: {
      message: 'Try dragging me around!',
      draggable: true,
      style: {
        background: 'linear-gradient(135deg, #f87171 0%, #dc2626 100%)',
        color: '#fff',
        borderRadius: '14px',
        fontWeight: '600',
        boxShadow: '0 12px 28px -10px rgba(220,38,38,0.45)',
      },
    },
  },
  {
    id: 'feature-promise',
    name: 'Promise Lifecycle',
    category: 'async',
    description: 'Handle loading, success, and error states',
    codeExample: `toast.promise(fetchData(), {\n  loading: 'Loading...',\n  success: 'Loaded!',\n  error: 'Failed!',\n}, {\n  style: {\n    background: 'linear-gradient(135deg, #818cf8 0%, #4f46e5 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(79,70,229,0.4)',\n  },\n});`,
    properties: {
      message: 'Promise lifecycle demo',
      style: {
        background: 'linear-gradient(135deg, #818cf8 0%, #4f46e5 100%)',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(79,70,229,0.4)',
      },
    },
  },
  {
    id: 'feature-lifecycle',
    name: 'Lifecycle Callbacks',
    category: 'async',
    description: 'Fire custom logic when the toast opens and closes (check your console)',
    codeExample: `toast({\n  message: 'Lifecycle hooks — see console',\n  autoClose: 3000,\n  onOpen: () => console.log('Toast opened'),\n  onClose: () => console.log('Toast closed'),\n  style: {\n    background: 'linear-gradient(135deg, #818cf8 0%, #4f46e5 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(79,70,229,0.4)',\n  },\n});`,
    properties: {
      message: 'Lifecycle hooks — see console',
      autoClose: 3000,
      onOpen: () => console.log('Toast opened'),
      onClose: () => console.log('Toast closed'),
      style: {
        background: 'linear-gradient(135deg, #818cf8 0%, #4f46e5 100%)',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(79,70,229,0.4)',
      },
    },
  },
  {
    id: 'feature-rtl',
    name: 'RTL Layout',
    category: 'interaction',
    description: 'Right-to-left layout — message on the right, robot on the left',
    codeExample: `toast({\n  message: 'مرحبا — RTL layout',\n  rtl: true,\n  robotVariant: wave,\n  style: {\n    background: 'linear-gradient(135deg, #f87171 0%, #dc2626 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 12px 28px -10px rgba(220,38,38,0.45)',\n  },\n});`,
    properties: {
      message: 'مرحبا — RTL layout',
      rtl: true,
      robotVariant: 'wave',
      style: {
        background: 'linear-gradient(135deg, #f87171 0%, #dc2626 100%)',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 12px 28px -10px rgba(220,38,38,0.45)',
      },
    },
  },
  {
    id: 'feature-near-screen',
    name: 'Away From Edge',
    category: 'interaction',
    description: 'Flip robot placement so the message sits closer to the screen edge',
    codeExample: `toast({\n  message: 'Robot sits away from the edge',\n  robotVariant: base,\n  nearScreen: false,\n  style: {\n    background: 'linear-gradient(135deg, #f87171 0%, #dc2626 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 12px 28px -10px rgba(220,38,38,0.45)',\n  },\n});`,
    properties: {
      message: 'Robot sits away from the edge',
      robotVariant: 'base',
      nearScreen: false,
      style: {
        background: 'linear-gradient(135deg, #f87171 0%, #dc2626 100%)',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 12px 28px -10px rgba(220,38,38,0.45)',
      },
    },
  },
  {
    id: 'feature-custom-style',
    name: 'Custom Styling',
    category: 'styling',
    description: 'Apply custom CSS styles inline',
    codeExample: `toast({\n  message: 'Styled toast',\n  style: {\n    background: 'linear-gradient(135deg, #2dd4bf 0%, #0d9488 100%)',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 14px 32px -12px rgba(13,148,136,0.5)',\n  },\n});`,
    properties: {
      message: 'Styled toast',
      style: {
        background: 'linear-gradient(135deg, #2dd4bf 0%, #0d9488 100%)',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 14px 32px -12px rgba(13,148,136,0.5)',
      },
    },
  },

  // Button variations
  {
    id: 'buttons-1',
    name: '1 Button',
    category: 'interaction',
    description: 'Toast with a single action button',
    codeExample: `toast({\n  message: 'Action needed',\n  buttons: [{\n    label: 'Done',\n    onClick: () => console.log('Clicked!'),\n    style: { background: '#3b82f6', color: '#fff' }\n  }],\n  style: {\n    background: '#1e293b',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(15,23,42,0.6)',\n  },\n});`,
    properties: {
      message: 'Action needed',
      buttons: [{ label: 'Done', onClick: () => {}, style: { background: '#3b82f6', color: '#fff' } }],
      style: {
        background: '#1e293b',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(15,23,42,0.6)',
      },
    },
  },
  {
    id: 'buttons-2',
    name: '2 Buttons',
    category: 'interaction',
    description: 'Toast with two action buttons',
    codeExample: `toast({\n  message: 'Something feels off... Are you sure, wanna keep going?',\n  buttons: [{\n    label: 'Yes, I am sure',\n    onClick: () => console.log('Confirmed'),\n    style: { background: 'black', color: '#fff' }\n  }, {\n    label: 'No, let me think',\n    onClick: () => console.log('Cancelled'),\n    style: { background: 'yellow', color: 'black' }\n  }],\n  robotVariant: 'dxd/pickachu.svg',\n  style: {\n    background: 'black',\n    color: 'yellow',\n    border: '1px solid yellow',\n    boxShadow: '0 10px 30px -10px rgba(15,23,42,0.6)',\n  },\n});`,
    properties: {
      message: 'Something feels off... Are you sure, wanna keep going?',
      buttons: [
        { label: 'Yes, I am sure', onClick: () => {}, style: { background: 'black', color: '#fff' } },
        { label: 'No, let me think', onClick: () => {}, style: { background: 'yellow', color: 'black' } },
      ],
      style: {
        background: 'black',
        color: 'yellow',
        border: '1px solid yellow',
        boxShadow: '0 10px 30px -10px rgba(15,23,42,0.6)',
      },
      robotVariant: 'dxd/pickachu.svg'
    },
  },
  {
    id: 'buttons-3',
    name: '3 Buttons',
    category: 'interaction',
    description: 'Toast with three action buttons',
    codeExample: `toast({\n  message: 'Choose option',\n  buttons: [{\n    label: 'Option 1',\n    onClick: () => {},\n    style: { background: '#ef4444', color: '#fff' }\n  }, {\n    label: 'Option 2',\n    onClick: () => {},\n    style: { background: '#3b82f6', color: '#fff' }\n  }, {\n    label: 'Option 3',\n    onClick: () => {},\n    style: { background: '#10b981', color: '#fff' }\n  }],\n  style: {\n    background: '#1e293b',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(15,23,42,0.6)',\n  },\n});`,
    properties: {
      message: 'Choose option',
      buttons: [
        { label: 'Option 1', onClick: () => {}, style: { background: '#ef4444', color: '#fff' } },
        { label: 'Option 2', onClick: () => {}, style: { background: '#3b82f6', color: '#fff' } },
        { label: 'Option 3', onClick: () => {}, style: { background: '#10b981', color: '#fff' } },
      ],
      style: {
        background: '#1e293b',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(15,23,42,0.6)',
      },
    },
  },
  {
    id: 'buttons-4',
    name: '4 Buttons',
    category: 'interaction',
    description: 'Toast with four action buttons',
    codeExample: `toast({\n  message: 'Multiple choices',\n  buttons: [{\n    label: 'A',\n    onClick: () => {},\n    style: { background: '#8b5cf6', color: '#fff' }\n  }, {\n    label: 'B',\n    onClick: () => {},\n    style: { background: '#ec4899', color: '#fff' }\n  }, {\n    label: 'C',\n    onClick: () => {},\n    style: { background: '#f59e0b', color: '#fff' }\n  }, {\n    label: 'D',\n    onClick: () => {},\n    style: { background: '#06b6d4', color: '#fff' }\n  }],\n  style: {\n    background: '#1e293b',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(15,23,42,0.6)',\n  },\n});`,
    properties: {
      message: 'Multiple choices',
      buttons: [
        { label: 'A', onClick: () => {}, style: { background: '#8b5cf6', color: '#fff' } },
        { label: 'B', onClick: () => {}, style: { background: '#ec4899', color: '#fff' } },
        { label: 'C', onClick: () => {}, style: { background: '#f59e0b', color: '#fff' } },
        { label: 'D', onClick: () => {}, style: { background: '#06b6d4', color: '#fff' } },
      ],
      style: {
        background: '#1e293b',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(15,23,42,0.6)',
      },
    },
  },
  {
    id: 'buttons-5',
    name: '5 Buttons',
    category: 'interaction',
    description: 'Toast with five action buttons',
    codeExample: `toast({\n  message: 'Many options',\n  buttons: [{\n    label: 'Btn 1',\n    onClick: () => {},\n    style: { background: '#3b82f6', color: '#fff' }\n  }, {\n    label: 'Btn 2',\n    onClick: () => {},\n    style: { background: '#10b981', color: '#fff' }\n  }, {\n    label: 'Btn 3',\n    onClick: () => {},\n    style: { background: '#f59e0b', color: '#fff' }\n  }, {\n    label: 'Btn 4',\n    onClick: () => {},\n    style: { background: '#ef4444', color: '#fff' }\n  }, {\n    label: 'Btn 5',\n    onClick: () => {},\n    style: { background: '#8b5cf6', color: '#fff' }\n  }],\n  style: {\n    background: '#1e293b',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(15,23,42,0.6)',\n  },\n});`,
    properties: {
      message: 'Many options',
      buttons: [
        { label: 'Btn 1', onClick: () => {}, style: { background: '#3b82f6', color: '#fff' } },
        { label: 'Btn 2', onClick: () => {}, style: { background: '#10b981', color: '#fff' } },
        { label: 'Btn 3', onClick: () => {}, style: { background: '#f59e0b', color: '#fff' } },
        { label: 'Btn 4', onClick: () => {}, style: { background: '#ef4444', color: '#fff' } },
        { label: 'Btn 5', onClick: () => {}, style: { background: '#8b5cf6', color: '#fff' } },
      ],
      style: {
        background: '#1e293b',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(15,23,42,0.6)',
      },
    },
  },
  {
    id: 'buttons-6',
    name: '6 Buttons',
    category: 'interaction',
    description: 'Toast with six action buttons',
    codeExample: `toast({\n  message: 'Maximum buttons',\n  buttons: [{\n    label: 'One',\n    onClick: () => {},\n    style: { background: '#3b82f6', color: '#fff' }\n  }, {\n    label: 'Two',\n    onClick: () => {},\n    style: { background: '#10b981', color: '#fff' }\n  }, {\n    label: 'Three',\n    onClick: () => {},\n    style: { background: '#f59e0b', color: '#fff' }\n  }, {\n    label: 'Four',\n    onClick: () => {},\n    style: { background: '#ef4444', color: '#fff' }\n  }, {\n    label: 'Five',\n    onClick: () => {},\n    style: { background: '#8b5cf6', color: '#fff' }\n  }, {\n    label: 'Six',\n    onClick: () => {},\n    style: { background: '#ec4899', color: '#fff' }\n  }],\n  style: {\n    background: '#1e293b',\n    color: '#fff',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -10px rgba(15,23,42,0.6)',\n  },\n});`,
    properties: {
      message: 'Maximum buttons',
      buttons: [
        { label: 'One', onClick: () => {}, style: { background: '#3b82f6', color: '#fff' } },
        { label: 'Two', onClick: () => {}, style: { background: '#10b981', color: '#fff' } },
        { label: 'Three', onClick: () => {}, style: { background: '#f59e0b', color: '#fff' } },
        { label: 'Four', onClick: () => {}, style: { background: '#ef4444', color: '#fff' } },
        { label: 'Five', onClick: () => {}, style: { background: '#8b5cf6', color: '#fff' } },
        { label: 'Six', onClick: () => {}, style: { background: '#ec4899', color: '#fff' } },
      ],
      style: {
        background: '#1e293b',
        color: '#fff',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -10px rgba(15,23,42,0.6)',
      },
    },
  },

  // other-style — dark minimalist toasts built from just `message` + `style`.
  // Icons are composed via color-emoji in the message; no padding, shared borderRadius.
  {
    id: 'other-default',
    name: 'other Default',
    category: 'other',
    description: 'Dark other base — white text on near-black with a subtle border',
    codeExample: `toast({\n  message: 'Event has been created',\n  style: {\n    background: '#0a0a0a',\n    color: '#fafafa',\n    border: '1px solid rgba(255,255,255,0.08)',\n    borderRadius: '14px',\n    boxShadow: '0 8px 24px rgba(0,0,0,0.5)',\n    fontSize: '14px',\n    fontWeight: '500',\n  },\n});`,
    properties: {
      message: 'Event has been created',
      style: {
        background: '#0a0a0a',
        color: '#fafafa',
        border: '1px solid rgba(255,255,255,0.08)',
        borderRadius: '14px',
        boxShadow: '0 8px 24px rgba(0,0,0,0.5)',
        fontSize: '14px',
        fontWeight: '500',
      },
    },
  },
  {
    id: 'other-success',
    name: 'other · Success',
    category: 'other',
    description: 'Dark card with a green accent — matches the other success look',
    codeExample: `toast({\n  message: '✅  Workspace activated successfully',\n  style: {\n    background: '#0a0a0a',\n    color: '#4ade80',\n    border: '1px solid rgba(74,222,128,0.25)',\n    borderRadius: '14px',\n    boxShadow: '0 8px 24px rgba(0,0,0,0.5)',\n    fontSize: '14px',\n    fontWeight: '600',\n  },\n});`,
    properties: {
      message: '✅  Workspace activated successfully',
      style: {
        background: '#0a0a0a',
        color: '#4ade80',
        border: '1px solid rgba(74,222,128,0.25)',
        borderRadius: '14px',
        boxShadow: '0 8px 24px rgba(0,0,0,0.5)',
        fontSize: '14px',
        fontWeight: '600',
      },
    },
  },
  {
    id: 'other-error',
    name: 'other · Error',
    category: 'other',
    description: 'Dark card with a red accent',
    codeExample: `toast({\n  message: '❌  Could not save your changes',\n  style: {\n    background: '#0a0a0a',\n    color: '#f87171',\n    border: '1px solid rgba(248,113,113,0.25)',\n    borderRadius: '14px',\n    boxShadow: '0 8px 24px rgba(0,0,0,0.5)',\n    fontSize: '14px',\n    fontWeight: '600',\n  },\n});`,
    properties: {
      message: '❌  Could not save your changes',
      style: {
        background: '#0a0a0a',
        color: '#f87171',
        border: '1px solid rgba(248,113,113,0.25)',
        borderRadius: '14px',
        boxShadow: '0 8px 24px rgba(0,0,0,0.5)',
        fontSize: '14px',
        fontWeight: '600',
      },
    },
  },
  {
    id: 'other-warning',
    name: 'other · Warning',
    category: 'other',
    description: 'Dark card with an amber accent',
    codeExample: `toast({\n  message: '⚠️  Double-check your input',\n  style: {\n    background: '#0a0a0a',\n    color: '#fbbf24',\n    border: '1px solid rgba(251,191,36,0.25)',\n    borderRadius: '14px',\n    boxShadow: '0 8px 24px rgba(0,0,0,0.5)',\n    fontSize: '14px',\n    fontWeight: '600',\n  },\n});`,
    properties: {
      message: '⚠️  Double-check your input',
      style: {
        background: '#0a0a0a',
        color: '#fbbf24',
        border: '1px solid rgba(251,191,36,0.25)',
        borderRadius: '14px',
        boxShadow: '0 8px 24px rgba(0,0,0,0.5)',
        fontSize: '14px',
        fontWeight: '600',
      },
    },
  },
  {
    id: 'other-info',
    name: 'other · Info',
    category: 'other',
    description: 'Dark card with a blue accent',
    codeExample: `toast({\n  message: '💡  Your file is being processed',\n  style: {\n    background: '#0a0a0a',\n    color: '#60a5fa',\n    border: '1px solid rgba(96,165,250,0.25)',\n    borderRadius: '14px',\n    boxShadow: '0 8px 24px rgba(0,0,0,0.5)',\n    fontSize: '14px',\n    fontWeight: '600',\n  },\n});`,
    properties: {
      message: '💡  Your file is being processed',
      style: {
        background: '#0a0a0a',
        color: '#60a5fa',
        border: '1px solid rgba(96,165,250,0.25)',
        borderRadius: '14px',
        boxShadow: '0 8px 24px rgba(0,0,0,0.5)',
        fontSize: '14px',
        fontWeight: '600',
      },
    },
  },
  {
    id: 'other-description',
    name: 'other · Description',
    category: 'other',
    description: 'Two-line toast — title + subtitle via newline in the message',
    codeExample: `toast({\n  message: '✅  Event created at Sunday, December 3rd at 9:30 PM',\n  style: {\n    background: '#0a0a0a',\n    color: '#fafafa',\n    border: '1px solid rgba(255,255,255,0.08)',\n    borderRadius: '14px',\n    boxShadow: '0 8px 24px rgba(0,0,0,0.5)',\n    fontSize: '14px',\n    fontWeight: '500',\n    whiteSpace: 'pre-line',\n    lineHeight: '1.5',\n  },\n});`,
    properties: {
      message: '✅  Event created\nSunday, December 3rd at 9:30 PM',
      style: {
        background: '#0a0a0a',
        color: '#fafafa',
        border: '1px solid rgba(255,255,255,0.08)',
        borderRadius: '14px',
        boxShadow: '0 8px 24px rgba(0,0,0,0.5)',
        fontSize: '14px',
        fontWeight: '500',
        whiteSpace: 'pre-line',
        lineHeight: '1.5',
      },
    },
  },
  {
    id: 'other-rich',
    name: 'other · Rich',
    category: 'other',
    description: 'Glassy gradient card with an inset highlight',
    codeExample: `toast({\n  message: '✨  New feature available',\n  style: {\n    background: 'linear-gradient(135deg, #18181b 0%, #27272a 100%)',\n    color: '#fafafa',\n    border: '1px solid rgba(255,255,255,0.08)',\n    borderRadius: '14px',\n    boxShadow: '0 10px 30px -8px rgba(0,0,0,0.5), inset 0 1px 0 rgba(255,255,255,0.08)',\n    fontSize: '14px',\n    fontWeight: '600',\n    letterSpacing: '0.01em',\n  },\n});`,
    properties: {
      message: '✨  New feature available',
      style: {
        background: 'linear-gradient(135deg, #18181b 0%, #27272a 100%)',
        color: '#fafafa',
        border: '1px solid rgba(255,255,255,0.08)',
        borderRadius: '14px',
        boxShadow: '0 10px 30px -8px rgba(0,0,0,0.5), inset 0 1px 0 rgba(255,255,255,0.08)',
        fontSize: '14px',
        fontWeight: '600',
        letterSpacing: '0.01em',
      },
    },
  },
] as const;
